# Generated by Django 4.2 on 2023-09-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINECAP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cnpj',
            field=models.CharField(max_length=200),
        ),
    ]
